# this file is automatically loaded when a New Game starts.
# it's a dummy map to send the player to the actual starting point.

[header]
width = -1
height = -1
heroPos = [-1, -1]

[[event]]
type = "Event"
location = [-1, -1, {w = -1, h = -1}]
activate = "OnLoad"
intermap = ["maps/Act1/RogueEncampment.toml", -1, -1, {seamless = false}]

