# it's a dummy map to represent the teleportation menu

[header]
width = -1
height = -1
heroPos = [-1, -1]

[[event]]
type = "Event"
location = [-1, -1, {w = -1, h = -1}]
activate = "OnTrigger"
hotspot = "Location"
intermap = ["maps/act1/RogueEncampment.toml", -1, -1]
soundfx = ["soundfx/environment/teleporter.ogg", {x = -1, y = -1, loop = false}]
tooltip = "Rogue Encampment"

[[event]]
type = "Event"
location = [-1, -1, {w = -1, h = -1}]
activate = "OnTrigger"
hotspot = "Location"
intermap = ["maps/act1/ColdPlains.toml", -1, -1]
requiresStatus = "D2swWaypointColdPlains"
soundfx = ["soundfx/environment/teleporter.ogg", {x = -1, y = -1, loop = false}]
tooltip = "Cold Plains"

